:::: progress
:::: {.progress-bar style="width: 100%;"}
::::
::::

# Curva Característica da Operação e Compimento Médio da Sequência

## Introdução

Especificar o plano amostral, a frequência de coleta e os limites de controle de um processo são algumas das decisões críticas na construção de gráficos de controle. Na inviabilidade de inspecionar todos os itens produzidos, são selecionados uma certa quantidade por lote de forma aleatória para composição das amostras. Naturalmente, quanto mais itens amostrados, maior a aproximação da representação real do processo e consequente maior controle. Logo, as alternativas viáveis são, ou tomar amostras pequenas com maior frequência, ou amostras grandes com menor frequência [@Carpinetti2003; @Montgomery2012Statistical]. 

A depender do número defeitos presentes, o lote pode ser aceito ou rejeitado, parelho ao teste de hipóteses:

$$
\left\{ \begin{array} HH_0: p = p_0\\ H_1: p \neq p_0 \end{array} \right.
$$

onde $p$ representa a proporção de defeitos na produção [@Botter2013].

Quando estabelecemos limites de controle afastados da linha central, aumentamos a tolerância do processo, diminuindo assim o risco de ocorrer pontos fora dos limites. Esse risco é denominado erro tipo I ($\alpha$) ou risco do produtor, responsável por indicar condições fora do controle sem causa atribuível (alarme falso).

A presença de baixos valores para o erro tipo I dificulta a detecção de defeitos reais, implicando no aumento de itens dentro dos limites de controle, quando o processo na realidade estiver fora de controle. A esse risco denominamos erro do tipo II ($\beta$) ou risco do consumidor. 

No caso de aproximação dos limites de controle da linha central gera o efeito contrário; quando o risco do produtor aumenta, o do consumidor diminui [@Montgomery2012Statistical; @Botter2013]. O cenário desejável é a identificação eficiente desses defeitos antes que ele seja repassado ao consumidor, garantindo a qualidade do produto.

Para um processo controlado sob condição de normalidade -- $X_{i} \sim N(\mu, \sigma^2)$ -- em um nível de operação ($L$) temos que a probabilidade do processo estar sob controle é dada por 

$$ 
P\left[LIC \leq \bar{X}_i \leq LSC \right] \Rightarrow P\left[\dfrac{\mu -L\sigma}{\sqrt{n}} \leq \bar{X}_i \leq \dfrac{\mu + L\sigma}{\sqrt{n}}\right],
$$
onde $LIC$ representa o limite inferior de controle e $LSC$, o limite superior de controle, $\sigma$ o desvio-padrão da operação e $n$, o número de amostras.
\
Para um processo operado em $3\sigma$ ($L=3$), temos que $$\therefore P\left[ \dfrac{\mu -3\sigma}{\sqrt{n}} \leq \bar{X}_i \leq \dfrac{\mu + 3\sigma}{\sqrt{n}}\right] = 0.9973.$$

Pela normalização dos dados -- $X_{i} \sim N(0, 1)$--, o erro tipo II corresponde a 99,73% e o erro tipo I a 0,27%. Em outras palavras, o processo acusará 27 alarmes falsos em 10.000 itens produzidos.
\

## Curva Característica da Operação (CCO)

## Compimento Médio da Sequência (CMS)


:::: progress
:::: {.progress-bar style="width: 100%;"}
::::
::::